{
  "openapi": "3.0.3",
  "info": {
    "title": "Case XP",
    "description": "API para o desafio do processo seletivo da XP Inc.",
    "version": "1.0.0"
  },
  "servers":[
    {
      "url": "https://case-xp-back-end.herokuapp.com",
      "description": "production"
    },
    {
      "url": "https://case-xp-back-end-staging.herokuapp.com",
      "description": "staging"
    },
    {
      "url": "https://case-xp-back-end-development.herokuapp.com",
      "description": "development"
    }
  ],
  "components": {
    "schemas": {
      "login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "email": "fulano.silva@email.com",
          "password": "12345678"
        }
      },
      "register": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "firstName": "Ciclano",
          "lastName": "Ferreira",
          "email": "beltrano.ferreira@email.com",
          "password": "12345678"
        }
      },
      "token": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string"
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJmdWxhbm8uc2lsdmFAZW1haWwuY29tIiwiaWF0IjoxNjU4NDA3MTAzLCJleHAiOjE2NTg0MDgwMDN9.85VmK2J7YQPQ9yX4iYt5ISyZjxhbfTTpbulIybyNwmQ"
        }
      },
      "user": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          }
        },
        "example": {
          "firstName": "Fulano",
          "lastName": "Silva"
        }
      },
      "balance": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "balance": {
            "type": "number"
          }
        },
        "example": {
          "id": 1,
          "balance": 1000
        }
      },
      "account": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "number"
          }
        },
        "example": {
          "amount": 100.25
        }
      },
      "allAssets": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number"
            },
            "ticker": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        "example": [
          {
            "id": 1,
            "ticker": "RRRP3",
            "name": "3R Petroleum"
          },
          {
            "id": 2,
            "ticker": "TTEN3",
            "name": "3tentos"
          }
        ]
      },
      "assets": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "number"
            },
            "assetId": {
              "type": "number"
            },
            "ticker": {
              "type": "string"
            },
            "quantity": {
              "type": "number"
            },
            "price": {
              "type": "number"
            },
            "change": {
              "type": "number"
            }
          }
        },
        "example": [
          {
            "userId": 1,
            "assetId": 42,
            "ticker": "AMBP3",
            "quantity": 100,
            "price": 25.34,
            "change": 2.26
          },
          {
            "userId": 1,
            "assetId": 407,
            "ticker": "PRIO3",
            "quantity": 200,
            "price": 22.26,
            "change": -0.58
          }
        ]
      },
      "asset": {
        "type": "object",
        "properties": {
          "userId": {
            "type": "number"
          },
          "assetId": {
            "type": "number"
          },
          "ticker": {
            "type": "string"
          },
          "quantity": {
            "type": "number"
          },
          "price": {
            "type": "number"
          },
          "change": {
            "type": "number"
          }
        },
        "example": {
          "userId": 1,
          "assetId": 407,
          "ticker": "PRIO3",
          "quantity": 200,
          "price": 22.26,
          "change": -0.58
        }
      },
      "order": {
        "type": "object",
        "properties": {
          "assetId": {
            "type": "number"
          },
          "quantity": {
            "type": "number"
          },
          "price": {
            "type": "number"
          }
        },
        "example": {
          "assetId": 348,
          "quantity": 100,
          "price": 1.85
        }
      },
      "position": {
        "type": "object",
        "properties": {
          "userId": {
            "type": "number"
          },
          "assetId": {
            "type": "number"
          },
          "quantity": {
            "type": "number"
          }
        },
        "example": {
          "userId": 1,
          "assetId": 348,
          "quantity": 100
        }
      },
      "operation": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number"
            },
            "userId": {
              "type": "number"
            },
            "type": {
              "type": "string"
            },
            "assetId": {
              "type": "number"
            },
            "quantity": {
              "type": "number"
            },
            "amount": {
              "type": "number"
            },
            "createdAt": {
              "type": "string"
            }
          }
        },
        "example": [
          {
            "id": 4,
            "userId": 1,
            "type": "DEPOSIT",
            "assetId": null,
            "quantity": null,
            "amount": 5000,
            "createdAt": "22/07/2022 16:19:00"
          },
          {
            "id": 6,
            "userId": 1,
            "type": "BUY",
            "assetId": 328,
            "quantity": 100,
            "amount": -5000,
            "createdAt": "22/07/2022 16:21:13"
          }
        ]
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "tags": [
    {
      "name": "login",
      "description": "Operações relacionadas ao login."
    },
    {
      "name": "register",
      "description": "Operações relacionadas à abertura de conta."
    },
    {
      "name": "user",
      "description": "Operações relacionadas à pessoa usuária."
    },
    {
      "name": "account",
      "description": "Operações relacionadas à conta digital."
    },
    {
      "name": "asset",
      "description": "Operações relacionadas a ativos."
    },
    {
      "name": "order",
      "description": "Operações relacionadas a ordens de compra e venda de ativos."
    },
    {
      "name": "operation",
      "description": "Operações relacionadas ao extrato da conta."
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "summary": "Realizar login",
        "description": "Autenticação da pessoa usuária e retorno de um token JWT.",
        "tags": ["login"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/login"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/token"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. Dados inseridos incorretamente."
          },
          "401": {
            "description": "Unauthorized. Senha incorreta."
          },
          "404": {
            "description": "Not Found. Pessoa usuária não cadastrada."
          }
        }
      }
    },
    "/register": {
      "post": {
        "summary": "Abrir conta",
        "description": "Cadastro da pessoa usuária e retorno de um token JWT.",
        "tags": ["register"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/register"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/token"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. Dados inseridos incorretamente."
          },
          "409": {
            "description": "Conflict. Pessoa usuária já possui conta."
          }
        }
      }
    },
    "/user": {
      "get": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Retornar o nome da pessoa usuária",
        "description": "Retorna o nome e sobrenome da pessoa usuária.",
        "tags": ["user"],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          },
          "404": {
            "description": "Not Found. Pessoa usuária não encontrada."
          }
        }
      }
    },
    "/account": {
      "get": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Retornar o saldo da conta",
        "description": "Retora o saldo atual da conta digital.",
        "tags": ["account"],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/balance"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          }
        }
      }
    },
    "/account/deposit": {
      "post": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Depositar dinheiro na conta",
        "description": "Realiza depósito de dinheiro na conta digital.",
        "tags": ["account"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/account"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/balance"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. Dados inseridos incorretamente."
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          },
          "404": {
            "description": "Not Found. Pessoa usuária não encontrada."
          }
        }
      }
    },
    "/account/withdraw": {
      "post": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Retirar dinheiro da conta",
        "description": "Realiza retirada de dinheiro da conta digital.",
        "tags": ["account"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/account"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/balance"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. Dados inseridos incorretamente."
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          },
          "422": {
            "description": "Unprocessable Entity. Saldo insuficiente."
          }
        }
      }
    },
    "/assets/all": {
      "get": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Retornar todos os ativos disponíveis",
        "description": "Retorna todos os ativos disponíveis na corretora.",
        "tags": ["asset"],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/allAssets"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          }
        }
      }
    },
    "/assets": {
      "get": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Retornar todos os ativos da pessoa usuária",
        "description": "Retorna todos os ativos que a pessoa usuária possui.",
        "tags": ["asset"],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/assets"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          }
        }
      }
    },
    "/assets/{assetId}": {
      "get": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Retornar um ativo específico",
        "description": "Retorna os dados de um ativo específico.",
        "tags": ["asset"],
        "parameters": [
          {
            "name": "assetId",
            "in": "path",
            "description": "asset ID",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/asset"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          },
          "404": {
            "description": "Not Found. Ativo indisponível na corretora."
          }
        }
      }
    },
    "/order/buy": {
      "post": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Enviar ordem de compra",
        "description": "Envia ordem de compra de um ativo.",
        "tags": ["order"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/order"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/position"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. Dados inseridos incorretamente."
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          },
          "404": {
            "description": "Not Found. Ativo indisponível na corretora."
          },
          "422": {
            "description": "Unprocessable Entity. Saldo insuficiente / Quantidade indisponível na corretora."
          }
        }
      }
    },
    "/order/sell": {
      "post": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Enviar ordem de venda",
        "description": "Envia ordem de venda de um ativo.",
        "tags": ["order"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/order"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/position"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request. Dados inseridos incorretamente."
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          },
          "404": {
            "description": "Not Found. Ativo não consta na carteira."
          },
          "422": {
            "description": "Unprocessable Entity. Quantidade insuficiente na carteira."
          }
        }
      }
    },
    "/operations": {
      "get": {
        "security": [{
          "bearerAuth": []
        }],
        "summary": "Verificar extrato da conta",
        "description": "Retorna extrato com todas as operações efetuadas.",
        "tags": ["operation"],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/operation"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Acesso não autorizado."
          }
        }
      }
    }
  }
}